import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import AuthContext from '../providers/AuthContext'
import bg from '@/public/bg.png';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {


  return (
    <html lang="en" style={{
      backgroundImage: `url(${bg.src})`,
      backgroundSize: 'cover',
      backgroundRepeat: 'no-repeat',
      backgroundPosition: 'center'
      }}>
        <body className={inter.className}>
          <AuthContext>
            <div>
              {children}
            </div>
          </AuthContext>
        </body>
    </html>
  )
}
